# Generated by Django 5.0 on 2026-06-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_remove_ticket_client_condition_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_condition_details',
            field=models.TextField(blank=True, db_column='health_condition_details', null=True),
        ),
    ]
